// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUNIDZuHq5PSCBAC535NAhDKxs8J8M-Og',
    appId: '1:186147360078:web:88b7ff6655028b8dc6621f',
    messagingSenderId: '186147360078',
    projectId: 'pokemonapp-82ba3',
    authDomain: 'pokemonapp-82ba3.firebaseapp.com',
    storageBucket: 'pokemonapp-82ba3.appspot.com',
    measurementId: 'G-S0BNGEDZ9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdmVKc6SZH5TqdS9ouBC4ki4ktrNmuyTo',
    appId: '1:186147360078:android:bfdfec0499c8db8bc6621f',
    messagingSenderId: '186147360078',
    projectId: 'pokemonapp-82ba3',
    storageBucket: 'pokemonapp-82ba3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA75yE24EM8fEclQzmyZi24Z6JA2di1CZY',
    appId: '1:186147360078:ios:6ebb268e0e435da5c6621f',
    messagingSenderId: '186147360078',
    projectId: 'pokemonapp-82ba3',
    storageBucket: 'pokemonapp-82ba3.appspot.com',
    iosBundleId: 'com.example.pokemonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA75yE24EM8fEclQzmyZi24Z6JA2di1CZY',
    appId: '1:186147360078:ios:6ebb268e0e435da5c6621f',
    messagingSenderId: '186147360078',
    projectId: 'pokemonapp-82ba3',
    storageBucket: 'pokemonapp-82ba3.appspot.com',
    iosBundleId: 'com.example.pokemonApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUNIDZuHq5PSCBAC535NAhDKxs8J8M-Og',
    appId: '1:186147360078:web:1888c89eecc0c4d8c6621f',
    messagingSenderId: '186147360078',
    projectId: 'pokemonapp-82ba3',
    authDomain: 'pokemonapp-82ba3.firebaseapp.com',
    storageBucket: 'pokemonapp-82ba3.appspot.com',
    measurementId: 'G-HX5H287DWL',
  );
}
